# Source :https://github.com/kartoza/docker-geoserver
version: '3'
volumes:
   geoserver-data:
    driver: local
    driver_opts: 
      type: none
      device: /data/geoserver_data
      o: bind
   geo-db-data:
    driver: local
    driver_opts: 
      type: none
      device: /data/geoserver_db
      o: bind
   spatial-data:
    driver: local
    driver_opts: 
      type: none
      device: /data/geoserver_layers
      o: bind

services:
   db:
      image: kartoza/postgis:${POSTGIS_VERSION_TAG}
      container_name: geoserver-db
      volumes:
         - geo-db-data:/var/lib/postgresql
      ports:
        - ${POSTGRES_PORT}:5432
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASS=${POSTGRES_PASS}
        - ALLOW_IP_RANGE=${ALLOW_IP_RANGE}
        - FORCE_SSL=FALSE
      restart: on-failure
      healthcheck:
        test: "exit 0"

   geoserver:
      image: kartoza/geoserver:${GEOSERVER_VERSION_TAG}
      container_name: geoserver
      volumes:
        - geoserver-data:/opt/geoserver/data_dir
        - spatial-data:/data/geoserver_layers
      ports:
        - ${GEOSERVER_PORT}:8080
      restart: on-failure
      environment:
        - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
        - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
        - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
        - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
        - INITIAL_MEMORY=${INITIAL_MEMORY}
        - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
        - STABLE_EXTENSIONS=${STABLE_EXTENSIONS}
        - COMMUNITY_EXTENSIONS=${COMMUNITY_EXTENSIONS}
        - GEOSERVER_CONTEXT_ROOT=${GEOSERVER_CONTEXT_ROOT}
      depends_on:
        - db
      healthcheck:
        test: curl --fail -s http://localhost:8080/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3